name: Build and Release Content

on: 
  push:
    paths:
      - 'docs/**'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Clear dist folder
        run: |
          rm -rf docs/.vitepress/dist/
      - name: Install and build
        run: |
          npm install
          npm run docs:build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        run: |
          aws s3 sync ./docs/.vitepress/dist s3://docs-vitepress.servicestack.net
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E3HOW7P0JDVHIV --paths "/*"
      - name: Deploy to GitHub Pages
        run: |
          cd docs/.vitepress/dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/.vitepress/dist

